site_name: fromistory
hooks:
  - overrides/.hooks/sort_posts_latest.py
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.expand
    - navigation.sections
    - toc.follow
  font:
    text: Open Sans
    code: JetBrains Mono
  favicon: assets/fromis-logo-white.svg
  logo: assets/fromis-logo-white.svg
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
  - stylesheets/fancybox.css
#  - https://cdn.jsdelivr.net/npm/@fancyapps/ui@6.0/dist/fancybox/fancybox.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/fancybox.umd.js
#  - https://cdn.jsdelivr.net/npm/@fancyapps/ui@6.0/dist/fancybox/fancybox.umd.js
#  - https://cdn.jsdelivr.net/npm/@fancyapps/ui@6.0/dist/panzoom/panzoom.umd.js
#  - Events:
#      - events/index.md
#  - events/171129.md
plugins:
  - redirects:
      redirect_maps:
        "index.md": "events/index.md"
  - search
#  - blog:
#      blog_dir: events
#      pagination: True
#      pagination_per_page: 1
#      blog_toc: True
#      post_readtime: false
#      post_date_format: MMMM d, yyyy hh:mm
#      post_url_format: "{slug}"
#      archive: false
#  - tags:
#      tags_file: events/tags.md